name: .NET Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Restore dependencies
        run: dotnet restore Test.sln
      - name: Build
        run: dotnet build Test.sln --configuration Release --no-restore 
      - name: Test
        run: dotnet test Test.sln --configuration Release --no-restore --no-build --verbosity normal
