name: .NET Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      # Append every DLL file that ends with 'Tests.dll' to the variable $x, then call 'dotnet test' with the DLLs to execute all the tests
      - name: Run Tests
        shell: powershell
        run: $x = ""; Get-ChildItem -path . -Recurse -Include *Tests.dll | where { $_.FullName -match "bin" }  | foreach { $x += " ""$_""" }; iex "dotnet test --logger ""trx;LogFileName=Results.trx"" $x"
